name: Test dspace on dev-5

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
  push:
    branches: [ "main" ]


jobs:
  test:
    runs-on: dspace-bbt

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: install requirements
        run: pip install -r requirements.txt

      - name: test
        run: python3.10 -m unittest -v 2> output.txt

      # multi line commands for future reference
      - name: Run a multi-line script
        run: |
          echo first line
          echo second line
